1.24.2

NumPy 1.24.2 is a maintenance release that fixes bugs and regressions
discovered after the 1.24.1 release. The Python versions supported by
this release are 3.8-3.11.

1.24.1

Bugfix release

1.24.0

NumPy 1.24.0 is now available. The highlights of the release are:

* New “dtype” and “casting” keywords for stacking functions.
* New F2PY features and fixes.
* Many new deprecations, check them out.
* Many expired deprecations,

The NumPy 1.24.0 release continues the ongoing work to improve the
handling and promotion of dtypes, increase execution speed, and
clarify the documentation. There are a large number of new and
expired deprecations due to changes in dtype promotion and cleanups.
It is the work of 177 contributors spread over 444 pull requests.
The supported Python versions are 3.8-3.11.


FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_casting_floatingpoint_errors.py::test_floatingpoint_errors_casting[longdouble-to-f8] - Failed: DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) were emitted.
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_getlimits.py::test_known_types - AssertionError:
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_nep50_promotions.py::test_nep50_weak_integers_with_inexact[g] - OverflowError: cannot convert longdouble infinity to integer
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_nep50_promotions.py::test_nep50_weak_integers_with_inexact[G] - OverflowError: cannot convert longdouble infinity to integer
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_numeric.py::TestFloatExceptions::test_floating_exceptions[g] - AssertionError: Type <class 'numpy.ndarray'> did not raise fpe error 'underflow'.
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_numeric.py::TestFloatExceptions::test_floating_exceptions[G] - AssertionError: Type <class 'numpy.complex256'> did not raise fpe error ''.
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data10-escape10-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735181aa5160>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data10-escape10-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351814c2e60>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data10-escape10-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848473e0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data11-escape11-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735184856520>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data11-escape11-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x73518485f6a0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data11-escape11-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735181588260>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data12-escape12-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735184866520>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data12-escape12-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735184871420>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data12-escape12-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x73518487f2a0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data13-escape13-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848872a0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data13-escape13-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735181588260>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data13-escape13-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x735184892da0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data14-escape14-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x73518489bde0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data14-escape14-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848a5de0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data14-escape14-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848899a0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data15-escape15-e-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848c3a60>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data15-escape15-f-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848d6b20>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestSpecialFloats::test_unary_spurious_fpexception[data15-escape15-d-log1p] - AssertionError: Got warnings: [<warnings.WarningMessage object at 0x7351848e1ae0>]
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestAVXUfuncs::test_avx_based_ufunc - AssertionError:
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::TestAVXFloat32Transcendental::test_sincos_float32 - AssertionError: Arrays are not almost equal up to 2 ULP (max difference is 67 ULP)
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/core/tests/test_umath.py::test_nextafter_0 - AssertionError
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/distutils/tests/test_log.py::test_log_prefix[info] - AssertionError: assert ''
FAILED .destdir/usr/pkg/lib/python3.11/site-packages/numpy/distutils/tests/test_log.py::test_log_prefix[debug] - AssertionError: assert ''
29 failed, 26625 passed, 1481 skipped, 1307 deselected, 35 xfailed, 2 xpassed, 40 warnings in 237.85s (0:03:57)
